/**
 * Extractor — dumps the full source Supabase schema to
 * `src/models/sql/{tables,indexes,functions,triggers,grants,rollback}.sql`.
 *
 * Usage:
 *   SOURCE_DATABASE_URL="postgres://..." npm run schema:dump
 *
 * The script connects **read-only** — no records are copied, no data is
 * touched. It emits pure PostgreSQL that Railway can consume unchanged.
 *
 * What it dumps
 *   - CREATE TABLE for every table in the public schema, with:
 *       columns (name, type, default, NOT NULL) preserved exactly,
 *       inline PRIMARY KEY / UNIQUE / CHECK constraints,
 *       FOREIGN KEYs (auth.users refs are rewritten to public.profiles),
 *       per-table GRANTs for role `app`.
 *   - Every non-primary-key index via `pg_get_indexdef()`.
 *   - Every function via `pg_get_functiondef()`.
 *   - Every trigger via `pg_get_triggerdef()`.
 *   - Rollback: DROP SCHEMA public CASCADE + recreate.
 *
 * Design notes
 *   - Uses only stdlib `pg` (already a dep) — no side-effect deps.
 *   - Emits SQL in dependency-safe order (enums→sequences→tables→FKs→indexes
 *     →functions→triggers) so `psql -f schema.sql` works standalone too.
 *   - Idempotent: overwrites the target files each run.
 *   - Filters out Supabase-managed noise: `pgsodium_masks`, `realtime.*`,
 *     `storage.*`, `auth.*`. Only touches `public`.
 */
import { Client } from "pg";
import { promises as fs } from "node:fs";
import path from "node:path";

const OUT_DIR = path.join(__dirname, "..", "src", "models", "sql");

async function dump() {
  const url = process.env.SOURCE_DATABASE_URL;
  if (!url) {
    console.error("SOURCE_DATABASE_URL is required.");
    process.exit(1);
  }

  const client = new Client({
    connectionString: url,
    ssl: { rejectUnauthorized: false },
    statement_timeout: 60_000,
  });
  await client.connect();

  await fs.mkdir(OUT_DIR, { recursive: true });

  // ---- Tables ----
  // We build CREATE TABLE from information_schema + pg_get_constraintdef so we
  // can rewrite auth.users foreign keys inline. pg_dump would be cleaner but
  // we can't shell out from Lovable Cloud.
  const tables = (
    await client.query<{ table_name: string }>(`
      SELECT c.relname AS table_name
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public' AND c.relkind = 'r'
      ORDER BY c.relname;
    `)
  ).rows.map((r) => r.table_name);

  let tablesSql = "-- Generated by scripts/dump-source-schema.ts\n\n";
  for (const t of tables) {
    const cols = (
      await client.query<{
        column_name: string;
        data_type: string;
        udt_name: string;
        is_nullable: "YES" | "NO";
        column_default: string | null;
      }>(
        `
        SELECT column_name, data_type, udt_name, is_nullable, column_default
        FROM information_schema.columns
        WHERE table_schema='public' AND table_name=$1
        ORDER BY ordinal_position
      `,
        [t],
      )
    ).rows;

    const colLines = cols.map((c) => {
      // Prefer udt_name for USER-DEFINED (enums) and array types
      let type: string;
      if (c.data_type === "USER-DEFINED") type = `public.${c.udt_name}`;
      else if (c.data_type === "ARRAY") type = `${c.udt_name.replace(/^_/, "")}[]`;
      else if (c.data_type === "timestamp with time zone") type = "timestamptz";
      else if (c.data_type === "timestamp without time zone") type = "timestamp";
      else if (c.data_type === "character varying") type = "text";
      else type = c.data_type;
      const parts = [`  "${c.column_name}"`, type];
      if (c.column_default) parts.push(`DEFAULT ${c.column_default}`);
      if (c.is_nullable === "NO") parts.push("NOT NULL");
      return parts.join(" ");
    });

    // Constraints (PK, UNIQUE, CHECK, FK) — FKs rewritten if they point at auth.users
    const cons = (
      await client.query<{ conname: string; contype: string; def: string }>(
        `
        SELECT conname, contype::text AS contype, pg_get_constraintdef(oid) AS def
        FROM pg_constraint
        WHERE conrelid = format('public.%I', $1)::regclass
        ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 WHEN 'f' THEN 3 ELSE 9 END,
                 conname
      `,
        [t],
      )
    ).rows;

    const conLines = cons.map((c) => {
      let def = c.def;
      if (c.contype === "f") {
        def = def.replace(/REFERENCES\s+auth\.users\s*\(id\)/gi, "REFERENCES public.profiles(id)");
        // Ensure we don't leave a CASCADE that would ripple into profile deletes
        if (!/ON DELETE/i.test(def)) def += " ON DELETE SET NULL";
      }
      return `  CONSTRAINT "${c.conname}" ${def}`;
    });

    tablesSql += `-- ----------- ${t} -----------\n`;
    tablesSql += `CREATE TABLE public."${t}" (\n`;
    tablesSql += [...colLines, ...conLines].join(",\n");
    tablesSql += `\n);\n`;
    tablesSql += `GRANT SELECT, INSERT, UPDATE, DELETE ON public."${t}" TO app;\n\n`;
  }
  await fs.writeFile(path.join(OUT_DIR, "tables.sql"), tablesSql);

  // ---- Indexes (skip PK indexes — already inline) ----
  const indexes = (
    await client.query<{ indexdef: string; indexname: string }>(`
      SELECT indexname, indexdef FROM pg_indexes
      WHERE schemaname='public'
        AND indexname NOT IN (
          SELECT conname FROM pg_constraint WHERE contype IN ('p','u')
            AND connamespace='public'::regnamespace
        )
      ORDER BY tablename, indexname;
    `)
  ).rows;
  await fs.writeFile(
    path.join(OUT_DIR, "indexes.sql"),
    "-- Generated by scripts/dump-source-schema.ts\n\n" +
      indexes.map((i) => i.indexdef + ";").join("\n") +
      "\n",
  );

  // ---- Functions ----
  const fns = (
    await client.query<{ def: string }>(`
      SELECT pg_get_functiondef(p.oid) AS def
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname='public'
      ORDER BY p.proname, pg_get_function_identity_arguments(p.oid);
    `)
  ).rows;
  await fs.writeFile(
    path.join(OUT_DIR, "functions.sql"),
    "-- Generated by scripts/dump-source-schema.ts\n\n" +
      fns.map((f) => f.def.trim() + ";").join("\n\n") +
      "\n",
  );

  // ---- Triggers ----
  const trigs = (
    await client.query<{ def: string }>(`
      SELECT pg_get_triggerdef(t.oid, true) AS def
      FROM pg_trigger t
      JOIN pg_class c ON c.oid = t.tgrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname='public' AND NOT t.tgisinternal
      ORDER BY c.relname, t.tgname;
    `)
  ).rows;
  await fs.writeFile(
    path.join(OUT_DIR, "triggers.sql"),
    "-- Generated by scripts/dump-source-schema.ts\n\n" +
      trigs.map((t) => t.def + ";").join("\n") +
      "\n",
  );

  await client.end();
  console.log(
    `Dumped: ${tables.length} tables, ${indexes.length} indexes, ${fns.length} functions, ${trigs.length} triggers → ${OUT_DIR}`,
  );
}

dump().catch((err) => {
  console.error(err);
  process.exit(1);
});
